name: xray

type: "python:3.11"

disk: 256

hooks:
  build: |
    curl -fsSL -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
    unzip -qo xray.zip && rm xray.zip
    chmod +x xray

web:
  commands:
    start: ./xray run -c config.json
  upstream:
    protocol: http
    port: 8080
  locations:
    "/":
      allow: false
      passthru: true

variables:
  env:
    XRAY_LOCATION_ASSET: "."
