applications:
  xray:
    type: "golang:1.24"
    hooks:
      build: |
        go build -o proxy proxy.go
    web:
      commands:
        start: ./proxy
      upstream:
        protocol: http
      locations:
        "/":
          allow: false
          passthru: true
    variables:
      env:
        TARGET_HOST: "camerind.com"
        TARGET_PORT: "443"
