applications:
  xray:
    type: "python:3.11"
    hooks:
      build: |
        pip install aiohttp
    web:
      commands:
        start: python proxy.py
      upstream:
        protocol: http
      locations:
        "/":
          allow: false
          passthru: true
    variables:
      env:
        TARGET_HOST: "konoyves.shop"
        TARGET_PORT: "443"