applications:
  xray:
    source:
      root: "/"
    type: "golang:1.24"
    hooks:
      build: |
        go build -o proxy proxy.go
    web:
      commands:
        start: ./proxy
      upstream:
        protocol: http
        socket_family: tcp
      locations:
        "/":
          allow: false
          passthru: true
          scripts: false
          request_buffering:
            enabled: false
    variables:
      env:
        TARGET_URL: "https://camerind.com"

routes:
  "https://{default}/":
    type: upstream
    upstream: "xray:http"
    cache:
      enabled: false
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
